Technology
Central-core-code/central-core pull request #6
Opened 2021-02-04 17:29 UTC by konradogielski

kolory zmienimy jak juz bedzie dzialal scroll, ale pytanie czy to robiomy jak page czy Component? w sumie szczegół no ale wiesz :D

2021-02-05 15:16 UTC, tomaszbryndzia requested changes

2021-02-05 15:16 UTC, tomaszbryndzia commented on components/OurTechnologyBlock.js
> +    <div className={("row", styles.technology__row)}>
normalnie dziala z (  ) ? Jesli tak to w sumie nawet lepiej niz pisanie do stringa

2021-02-05 15:16 UTC, tomaszbryndzia commented on pages/ourTechnology.js
> +  } = translations[locale].ourTechnologyBlock;
Ja na moje skoro w trsanslacjach nazywa juz opisowo. To samo tlumaczenie mozna skrocic typu `jsTechDesc` , `jsDesc`, `jsTech`

2021-02-05 15:16 UTC, tomaszbryndzia commented on pages/ourTechnology.js
> +          title={"JS"}
nie potrzebne ci bracketsy jak dajesz w stringu

2021-02-05 15:55 UTC, konradogielski commented on components/OurTechnologyBlock.js
> +    <div className={("row", styles.technology__row)}>
no wlasnie nie działa i zapomniałem to poprawić :D

2021-02-07 12:49 UTC, tomaszbryndzia approved these changes

2021-02-07 12:49 UTC, merged